repos:
  - repo: local
    hooks:
      - id: mypy
        name: mypy
        entry: mypy
        language: system
        types: [python]
        require_serial: true
        additional_dependencies: []
      - id: black
        name: black
        entry: black
        language: system
        types: [python]
        require_serial: true
